#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar 11 01:14:38 2018

@author: sam
"""


while a < b and b < c:
    py_trip = (a ** 2) + (b ** 2)
    if py_trip == c ** 2:
        print(py_trip)
    
    else:
        print("Not Pythagorean Triplet")    